apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/khumozin/news-api-gitops-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: news-api

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true