apiVersion: v1
kind: Namespace
metadata:
  name: news-api
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: news-api-sa
  namespace: news-api
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: news-api-ingressroute-certificate
  namespace: news-api
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: news-api-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - news-api.khumo.cloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-api
  namespace: news-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-api
  template:
    metadata:
      labels:
        app: news-api
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "news-api-role"
        vault.hashicorp.com/agent-inject-secret-NEWS_API_KEY: "secret/data/news-api"
        vault.hashicorp.com/agent-inject-template-NEWS_API_KEY: |
          {{- with secret "secret/data/news-api" -}}
          {{ .Data.data.NEWS_API_KEY }}
          {{- end }}
    spec:
      serviceAccountName: news-api-sa
      containers:
        - name: news-api
          image: khumo/news-api:v1.0.3
          ports:
            - containerPort: 3000
          env:
            - name: NEWS_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: news-api
                  key: NEWS_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: news-api
  namespace: news-api
spec:
  selector:
    app: news-api
  ports:
    - port: 80
      targetPort: 3000
